[language-server.rust-analyzer.config]
# cargo.noDefaultFeatures = true
diagnostics.disabled = ["inactive-code"]

[language-server.eye]
command = "eye"
args = ["lsp"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "eye"
scope = "source.eye"
file-types = ["eye"]
roots = ["main.eye"]
comment-token = "#"
language-servers = ["eye"]
grammar = "eye"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "gon"
scope = "source.gon"
file-types = ["gon"]
roots = []
comment-token = "//"
#grammar = "gon"

[[grammar]]
name = "eye"
source.path = "/home/linus/dev/tree-sitter-eye"
#source.git = "https://github.com/LinusDikomey/tree-sitter-eye"

#[[grammar]]
#name = "gon"
#source.path = "~/dev/tree-sitter-gon"
