[language-server.rust-analyzer.config]
# cargo.noDefaultFeatures = true
diagnostics.disabled = ["inactive-code"]
check.command = "clippy"

[language-server.eye]
command = "eye"
args = ["lsp"]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "eye"
scope = "source.eye"
file-types = ["eye"]
roots = ["main.eye"]
comment-token = "#"
block-comment-tokens = [
  { start = "#-", end = "-#" }
]
language-servers = ["eye"]
grammar = "eye"
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'[' = ']'
'{' = '}'
'"' = '"'

[[grammar]]
name = "eye"
source.path = "/home/linus/dev/tree-sitter-eye"
#source.git = "https://github.com/LinusDikomey/tree-sitter-eye"

[[language]]
name = "gon"
scope = "source.gon"
file-types = ["gon"]
roots = []
comment-token = "//"
#grammar = "gon"

#[[grammar]]
#name = "gon"
#source.path = "~/dev/tree-sitter-gon"

[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--line-length", "100", "--quiet", "-"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "latex"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
text-width = 99
