#!/bin/bash

set -e

echo "Installing Linus' Arch Linux i3 Config"
echo "This should be run as the user everything should be installed for"
read -p "press Enter to continue ..."

cd ~
mkdir .config

echo "Updating system"
sudo pacman -Syu

echo "Installing development packages"
sudo pacman -S --needed base-devel git rustup

echo "Installing nightly rust"
rustup default nightly

echo "Cloning paru"
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si

cd ~
rm -rf paru

echo "Cloning dotfiles"
git clone git@github.com:LinusDikomey/dotfiles

cd dotfiles

echo "Installing packages"
paru -S $(cat packages)

echo "Setting shell to fish"
chsh -s /bin/fish

echo "Linking configs"
cd ~/.config
ln -s ~/dotfiles/alacritty
ln -s ~/dotfiles/dunst
ln -s ~/dotfiles/feh
ln -s ~/dotfiles/fish
ln -s ~/dotfiles/i3
ln -s ~/dotfiles/lazygit
ln -s ~/dotfiles/nvim
ln -s ~/dotfiles/polybar
ln -s ~/dotfiles/redshift
ln -s ~/dotfiles/rofi
ln -s ~/dotfiles/tmux
ln -s ~/dotfiles/picom.conf

echo "Enabling sddm"
systemctl enable sddm

echo "Enabling NetworkManager"
systemctl enable NetworkManager

echo "Seting up sddm"
sddm_login_prompt=$(read -p "Enter Login Text: ")
sudo ~/dotfiles/scripts/setup_sddm /usr/share/wallpaper.png "$sddm_login_prompt"

echo
echo "Installation is completed!"
echo
echo "You can set a wallpaper by placing it in ~/.config/wallpaper.png"
echo "Have fun :D"
