#!/bin/bash

set -e

echo "Installing Linus' Arch Linux i3 Config"
echo "This should be run as the user everything should be installed for"
echo "You are $(whoami), correct?"
read -p "press Enter to continue ..."

cd ~
mkdir -p .config

echo "Updating system"
sudo pacman -Syu

echo "Installing development packages"
sudo pacman -S --needed base-devel git rustup

echo "Installing nightly rust"
rustup default nightly

if command -v paru &> /dev/null ; then
    echo "paru already exists, skipping step"
else
    echo "Cloning and building paru"
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si
    cd ~
    rm -rf paru
fi

if [ -d "dotfiles" ] ; then
    echo "dotfiles folder already exists, skipping clone"
else
    echo "Cloning dotfiles"
    git clone git@github.com:LinusDikomey/dotfiles
fi

cd dotfiles

echo "Installing packages"
paru -S $(cat packages)

echo "Setting shell to fish"
chsh -s /bin/fish

echo "Setting git configs"
git config --global core.editor nvim
git config --global url.git@github.com:.insteadof https://github.com/

echo "Linking configs"
./scripts/link_configs

echo "Enabling sddm"
sudo systemctl enable sddm

echo "Enabling NetworkManager"
sudo systemctl enable NetworkManager

echo "Seting up sddm"
sddm_login_prompt=$(read -p "Enter Login Text: ")
sudo ~/dotfiles/scripts/setup_sddm /usr/share/wallpaper.png "$sddm_login_prompt"

echo
echo "Installation is completed!"
echo
echo "You can set a wallpaper by placing it in /usr/share/wallpaper.png"
echo "Have fun :D"

neofetch
