#!/bin/bash

while [ 1 ]
do
    updates=$(checkupdates | wc -l)

    if [ $updates -ne 0 ]; then
        echo "<span foreground='#12FF39'>󰚰 </span> ${updates}"
    else
        echo ""
    fi
    sleep 60
done
