#!/bin/bash

mkdir -p ~/git

cd ~/git
echo "Cloning helix"
git clone https://github.com/helix-editor/helix
cd helix
git pull
echo "Building and installing helix"
HELIX_DISABLE_AUTO_GRAMMAR_BUILD=1 cargo install --path helix-term --locked
echo "copying runtime dir"
rm -rf ~/dotfiles/config/helix/runtime/
