#!/bin/bash
set -e

export version=v0.7.3
export theme=Catppuccin-Mocha-Standard-Blue-Dark

if [ ! -e "~/.themes/${theme}" ]; then
  mkdir -p ~/.themes
  curl -L https://github.com/catppuccin/gtk/releases/download/${version}/{$theme}.zip -o ~/.themes/catppuccin.zip
  unzip ~/.themes/catppuccin.zip -d ~/.themes/
  rm -rf ~/.themes/catppuccin.zip
fi
