#!/bin/bash
set -e

# This script runs during install as root with the path to the wallpaper as it's argument
wallpaper_path=$1
text=$2
echo "Setting SDDM theme to sugar-candy and the theme's wallpaper path to $wallpaper_path"
cat /etc/sddm.conf.d/sddm.conf | sed "s/^Current=.*/Current=sugar-candy/" > sddm_conf
cat sddm_conf > /etc/sddm.conf.d/sddm.conf
rm sddm_conf
cat /usr/share/sddm/themes/sugar-candy/theme.conf | sed "s#^Background=.*#Background=\"$wallpaper_path\"#" | sed "s#^HeaderText=.*#HeaderText=\"$text\"#" > theme_conf
cat theme_conf > /usr/share/sddm/themes/sugar-candy/theme.conf
rm theme_conf

echo "SDDM is now ready to go!"
